### ISSUE TITLE
Github ubuntu linux installation

### ISSUE THREAD

**Issue by leshchenko1979** [staticjinja/staticjinja#133]
I'm trying to run staticjinja from a github workflow script:

```yaml
...
    steps:
      - uses: actions/checkout@v2
      - run: pip install staticjinja && staticjinja build
...
```

However, after a successful installation of staticjinja (`pip install staticjinja`) I get an error trying to run `staticjinja build`:
```
...
Successfully installed docopt-0.6.2 easywatch-0.0.5 staticjinja-1.0.3 watchdog-1.0.2
/home/runner/work/_temp/e2263f86-a480-4903-8010-703fbf96db29.sh: line 1: staticjinja: command not found
Error: Process completed with exit code 127.
```

What am I doing wrong?

**Comment by NickCrews** [comment]
Hi! Sorry, just saw this.

I'm not immediately sure. Have you been able to do this in a previous version of staticjinja? I've been making some changes, but nothing that seems related to packaging and the CLI entry point (since I think that is the problem, it's not some internal problem inside staticjinja, it's that the CLI entrypoint simply isn't being installed...).

As some sanity checks, what OS and and python version do you have your runner set up with? (though I imagine this isn't important 😢 )

I can try to look into this more.

**Comment by NickCrews** [comment]
In the test PR #135, I wasn't able to reproduce. See the result of the action at https://github.com/staticjinja/staticjinja/runs/1803018502. I do notice that although that run also installed SJ 1.0.3 like yours did, it did install other versions of the other dependencies. I'd guess this might be because of differing python versions? My test used python 3.9.1. Again, knowing your python version might be helpful for me to try to reproduce.

Also, if you could give the entire contents of your action yaml, or give me the link to your failed action run, either of those would also be helpful.

**Comment by leshchenko1979** [comment]
Hi!

Here's the full log for the action:
```
Run pip install staticjinja && staticjinja build
12
Collecting staticjinja
13
  Downloading staticjinja-1.0.3-py2.py3-none-any.whl (10 kB)
14
Collecting docopt
15
  Downloading docopt-0.6.2.tar.gz (25 kB)
16
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from staticjinja) (2.10.1)
17
Collecting easywatch
18
  Downloading easywatch-0.0.5.tar.gz (2.9 kB)
19
Collecting watchdog
20
  Downloading watchdog-1.0.2-py3-none-manylinux2014_x86_64.whl (72 kB)
21
Building wheels for collected packages: docopt, easywatch
22
  Building wheel for docopt (setup.py): started
23
  Building wheel for docopt (setup.py): finished with status 'done'
24
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13704 sha256=4accd09eddf8ad94c881ef613decd51980f3363c9f247495b2d65caa2537fb55
25
  Stored in directory: /home/runner/.cache/pip/wheels/56/ea/58/ead137b087d9e326852a851351d1debf4ada529b6ac0ec4e8c
26
  Building wheel for easywatch (setup.py): started
27
  Building wheel for easywatch (setup.py): finished with status 'done'
28
  Created wheel for easywatch: filename=easywatch-0.0.5-py3-none-any.whl size=3007 sha256=efbf266d084d314e6fc21338a13eac01dcfd6884ce2a594fb5ebe758d15a5740
29
  Stored in directory: /home/runner/.cache/pip/wheels/23/f9/3f/9ba6110942a25ec369c8dfb1e59471e5d9bb56279224a10f5a
30
Successfully built docopt easywatch
31
Installing collected packages: docopt, watchdog, easywatch, staticjinja
24
  WARNING: The script watchmedo is installed in '/home/runner/.local/bin' which is not on PATH.
25
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
26
  WARNING: The script staticjinja is installed in '/home/runner/.local/bin' which is not on PATH.
27
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
28
Successfully installed docopt-0.6.2 easywatch-0.0.5 staticjinja-1.0.3 watchdog-1.0.2
29
/home/runner/work/_temp/ab616b78-9a76-4df5-a8b8-b7aba38dad65.sh: line 1: staticjinja: command not found
```

And here's the workflow file:
```yaml
name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install staticjinja && staticjinja build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CIAN_PARSE }}'
          channelId: live
          projectId: cian-parse
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

As you can see, neither python version nor operating system are set, so I assume by default they are Ubuntu / Python 3.9.
